opt_in_rules:
  - conditional_binding_cascade
disabled_rules:
  - closing_brace
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - nesting
  - statement_position
  - type_body_length
  - type_name
  - variable_name
colon: error
comma: error
conditional_binding_cascade: error
control_statement: error
empty_count: error
force_try: error
leading_whitespace: error
legacy_constant: error
legacy_constructor: error
line_length:
 - 120
 - 140
opening_brace: error
operator_whitespace: error
return_arrow_whitespace: error
trailing_newline: error
trailing_semicolon: error
trailing_whitespace: error
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
